/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppQueensRouteImport } from './routes/_app.queens'
import { Route as AppPointsRouteImport } from './routes/_app.points'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppHivesRouteImport } from './routes/_app.hives'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppApiaryRouteImport } from './routes/_app.apiary'
import { Route as AppPointsPointIdRouteImport } from './routes/_app.points.$pointId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppQueensRoute = AppQueensRouteImport.update({
  id: '/queens',
  path: '/queens',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsRoute = AppPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppHivesRoute = AppHivesRouteImport.update({
  id: '/hives',
  path: '/hives',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppApiaryRoute = AppApiaryRouteImport.update({
  id: '/apiary',
  path: '/apiary',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsPointIdRoute = AppPointsPointIdRouteImport.update({
  id: '/$pointId',
  path: '/$pointId',
  getParentRoute: () => AppPointsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/apiary': typeof AppApiaryRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/hives': typeof AppHivesRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/points': typeof AppPointsRouteWithChildren
  '/queens': typeof AppQueensRoute
  '/points/$pointId': typeof AppPointsPointIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/apiary': typeof AppApiaryRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/hives': typeof AppHivesRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/points': typeof AppPointsRouteWithChildren
  '/queens': typeof AppQueensRoute
  '/': typeof AppIndexRoute
  '/points/$pointId': typeof AppPointsPointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/apiary': typeof AppApiaryRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/hives': typeof AppHivesRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/points': typeof AppPointsRouteWithChildren
  '/_app/queens': typeof AppQueensRoute
  '/_app/': typeof AppIndexRoute
  '/_app/points/$pointId': typeof AppPointsPointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apiary'
    | '/calendar'
    | '/chat'
    | '/hives'
    | '/marketplace'
    | '/points'
    | '/queens'
    | '/points/$pointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/apiary'
    | '/calendar'
    | '/chat'
    | '/hives'
    | '/marketplace'
    | '/points'
    | '/queens'
    | '/'
    | '/points/$pointId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/apiary'
    | '/_app/calendar'
    | '/_app/chat'
    | '/_app/hives'
    | '/_app/marketplace'
    | '/_app/points'
    | '/_app/queens'
    | '/_app/'
    | '/_app/points/$pointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queens': {
      id: '/_app/queens'
      path: '/queens'
      fullPath: '/queens'
      preLoaderRoute: typeof AppQueensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points': {
      id: '/_app/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AppPointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hives': {
      id: '/_app/hives'
      path: '/hives'
      fullPath: '/hives'
      preLoaderRoute: typeof AppHivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apiary': {
      id: '/_app/apiary'
      path: '/apiary'
      fullPath: '/apiary'
      preLoaderRoute: typeof AppApiaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/$pointId': {
      id: '/_app/points/$pointId'
      path: '/$pointId'
      fullPath: '/points/$pointId'
      preLoaderRoute: typeof AppPointsPointIdRouteImport
      parentRoute: typeof AppPointsRoute
    }
  }
}

interface AppPointsRouteChildren {
  AppPointsPointIdRoute: typeof AppPointsPointIdRoute
}

const AppPointsRouteChildren: AppPointsRouteChildren = {
  AppPointsPointIdRoute: AppPointsPointIdRoute,
}

const AppPointsRouteWithChildren = AppPointsRoute._addFileChildren(
  AppPointsRouteChildren,
)

interface AppRouteChildren {
  AppApiaryRoute: typeof AppApiaryRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppHivesRoute: typeof AppHivesRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppPointsRoute: typeof AppPointsRouteWithChildren
  AppQueensRoute: typeof AppQueensRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiaryRoute: AppApiaryRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppHivesRoute: AppHivesRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppPointsRoute: AppPointsRouteWithChildren,
  AppQueensRoute: AppQueensRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
